# Generated by Django 3.2.8 on 2022-08-10 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4e836b1-851d-4e36-bb1b-520303f2282b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
