# Generated by Django 3.2.8 on 2022-08-14 16:19

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41146bc5-6994-4121-ac74-93684e46e69e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
